EOSIO/eosjs

- src/index.js
- src/index.test.js
this makes it easy for library users to check the current version,
e.g. for debugging and adding the version number to stack traces.
tested for node and the browser:
> expose current version number

- .gitignore
- README.md
@jcalfee this PR accomplishes 2 things
1. Intellij project directories will be ignored
2. Adds notice to the read me that eosjs currently supports dawn 2.x and educates users where they can find the current stable eos branch to work with while we build out 3.x support
> Dawn 2x support notice

- src/structs.js
Signatures could not be rebuilt ( L:321, L:328, L:333, L:342 ) due to ecc not being imported and returning undefined.
```
ReferenceError: ecc is not defined user.sig action.data transaction.actions
at Object.fromObject (D:\Work\Websites\scatter-hackathon\node_modules\eosjs\lib\structs.js:414:23)
```
(Note, this fix is untested on the library itself, only within the transpiled code)
```
var _require = require('eosjs-ecc'),
ecc = _require,
PublicKey = _require.PublicKey;
```
> Importing ecc

- src/index.js
Since v15 `UDecimalPad` is used heavily when developing an
application. By making the formatter available on the instance we
can conveniently use them in functions which receive an eos
instance by dependency injection.
> format: include on instance

- README.md
- src/structs.js
- src/structs.test.js
Please consider merging this fix to prevent returning wrong authority string if this is a non-EOS prefix. Similar patches were merged and pushed to npm for related issues in eosjs-ecc, as confirmed in closed PRs https://github.com/EOSIO/eosjs-ecc/pull/30 and https://github.com/EOSIO/eosjs-ecc/pull/32
Can we get this merged and pushed to npm as soon as possible?
> Fix to prevent returning wrong authority string if this is a non-EOS prefix (e.g. TLOS)

- src/structs.js
- src/write-api.js
This PR replaces all new Buffer which is deprecated and unsafe with Buffer.from
We should not use deprecated/unsafe Buffer constructor.
The behavior of new Buffer() is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or Buffer initialization is not performed.
To make the creation of Buffer instances more reliable and less error-prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.
Check this out: https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
> new Buffer is deprecated and unsafe

- src/eosjs-api.ts
- src/eosjs-jsonrpc.ts
Moved base64ToBinary logic into getRawAbi wrapper function for `/v1/chain/get_raw_code_and_abi` and created interface to an optional abiProvider
> added optional abiProvider to Api constructor

- src/eosjs-api-interfaces.ts
- src/eosjs-api.ts
- src/eosjs-jssig.ts
- src/tests/eosjs-jssig.test.ts
Signature providers may have valid reasons to modify a transaction (i.e., add actions) prior to returning it to the API `transact` method for possible broadcast. This is not possible currently, as they only return signatures, and `transact` uses the same serialized transaction that was passed into the signature provider.
In this PR, the signature provider returns an object with two keys: `signatures` and `serializedTransaction`. `transact` then broadcasts this output.
> Signature Providers: Return transaction along with signatures

- .travis.yml
- package.json
- scripts/publish.sh
This will publish the output of the eosjs web build to a CDN for consumption.  
This also removes the prepublish step in the package.json due to deprecation
> deploys eosjs web build to cdn

- scripts/publish.sh
In cases when a tag contains `-beta`, then we should still publish to NPM, but we should do it with the beta tag.
> assigns beta tag to npm package for beta git tag

- src/ripemd.es5.js
- src/ripemd.js
@tbfleming @chris-allnutt 
Please refer this pull request to https://github.com/EOSIO/eosjs2/issues/76
I am proposing the fix here since we have migrated eosjs2 to this repo.
Background:
While calculating the RIPEMD160 hash with `ripemd.js` in eosjs, `Proxy` is used during the calculation. `Proxy` is not supported in IE11 hence eosjs did not work in IE11.
https://github.com/EOSIO/eosjs/blob/master/src/ripemd.js#L382
https://github.com/EOSIO/eosjs/blob/master/src/ripemd.es5.js#L331
Fix:
Replace the way to access the DataView object with an anonymous function instead of a Proxy. Access it by calling the function directly.
Test:
I have put about 10 input cases for the fixed ripemd160 hash function and the result values are same as the original.
I have included the fix locally for the …
> Replace the use of "Proxy" in ripemd.js to make eosjs compatible to IE11

- src/eosjs-serialize.ts
When using extended_asset, if type of data to quantity is string, an error of 'undefined' occurs.
For example, when using 'extened_asset', send data to quantity with '1.000 EOS', an error occurs. it wants to throw an error and express it explicitly.
> Add checking type of data to serializeStruct

- .travis.yml
- scripts/publish.sh
This is an incremental change to the publish process for eosjs.  This will publish the HEAD of the develop branch as an NPM with the `edge` tag.  The version of the package.json is incremented with with the `prerelease` option.  With the current state of the package.json, this will look like:
v20.0.0-beta2.0
Subsequent commits against the develop branch will continue to increment the prerelease version number:
v20.0.0-beta2.1
v20.0.0-beta2.2
and so on.  
Those interested in utilizing the latest commits to the develop branch can run `npm install eosjs@edge`
> publish develop branch with edge tag

- .travis.yml
- package.json
To address https://github.com/EOSIO/eosjs/issues/447, we are temporarily removing the auto-deployments of eosjs@edge
> removes deployment

- .travis.yml
- scripts/publish.sh
This restores edge releases for eosjs.  Commits to the `develop` branch will push an `@edge` version to npm that contains the short commit has that was published.  For example:
If the current version is 1.0.0
Commit 1 with commit hash c8a134 is pushed to develop.  Performing an `npm install eosjs@edge` would pull in 1.0.1-c8a134.0.
This also updates the version of NPM used for builds to 6.4.1 to gain access to the `preid` functionality in `npm version`
> Restores Edge Releases

- README.md
- docs/4.-Reading blockchain-Examples.md
- src/eosjs-jsonrpc.ts
- src/tests/eosjs-jsonrpc.test.ts
- src/tests/web.html
- Support `reverse` and `show_payer` option in `JsonRpc`
- Remove trailing spaces
- Update examples in the document
- Tested on JungleNet and works fine
- [getTableRows in Descending order #324](https://github.com/EOSIO/eosjs/issues/324)
- [Merge pull request #6264 from taokayan/get_table_reverse](https://github.com/EOSIO/eos/blob/ea08cfd3d1a82b634a9e84f971d99708af516c0d/plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp#L263)
> Update: Support reverse order and show payer option - Fix #324

- README.md
- docs/2.-Transaction-Examples.md
Fixes `TypeError: JsSignatureProvider is not a constructor` for NodeJS and Babel.
Caused by `export default class JsSignatureProvider`.
Babel assigns default exports to the default property. 
So if you use require to import ES6 modules, you need to access the default property.
> Correct import of default property

- .npmignore
Benefits include:
- More concise syntax
- Better readability
- More generic selectors
> verbose npmignore -> concise npminclude

- .npmignore
- src/index.ts
- webpack.debug.js
- webpack.prod.js
- Reexport out `* as numeric` in index file
- Include `eosjs_numeric` as a module in the web build
> Export Numeric functions in Index

- src/eosjs-jsonrpc.ts
- src/tests/eosjs-jsonrpc.test.ts
This PR adds support for `/v1/chain/get_scheduled_transactions` to JSON-RPC. (EOSIO/eos#4470)
`get_scheduled_transactions(json: boolean, lowerBound: string, limit: number)` is added.
New API is added, and its usage needs to be documented.
> Add `get_scheduled_transactions` to jsonrpc

- src/eosjs-api-interfaces.ts
- src/eosjs-api.ts
- src/eosjs-jsonrpc.ts
- src/eosjs-jssig.ts
- src/eosjs-rpc-interfaces.ts
Add support for context-free data in transactions. Signature providers may optionally support this. `eosjs-jssig.ts` supports it.
Several functions and interfaces now have optional fields for handling context-free data.
Overview of context-free actions and context-free data:
* Context-free data is an optional transaction field containing `bytes[]` (array of array of 8-bit values)
* Context-free actions in contracts may reference this data, but normal actions may not
* Context-free actions are similar to normal actions, but may not reference state. This includes, but is not limited to: tables, authorizations, current time, etc.
* ABI 1.0 and ABI 1.1 do not describe context-free data; it's opaque
* ABI 1.0 and ABI 1.1 do not distinguish between normal and context-free actions. It's up to …
> Handle context-free data

- src/eosjs-api.ts
Modified the conditional in `hasRequiredTaposFields` to use `typeof() === 'number'` instead of a truthiness check for the fields.  As seen in the excerpt below from the transaction header file, both of these fields are unsigned integers and should be confirmed as numbers to allow the 0 case to pass.
```
uint16_t               ref_block_num       = 0U; ///< specifies a block num in the last 2^16 blocks.
uint32_t               ref_block_prefix    = 0UL; ///< specifies the lower 32 bits of the blockid at get_ref_blocknum
```
Addresses #554
> Fix tapos check

- package.json
- src/eosjs-jsonrpc.ts
- src/eosjs-rpc-interfaces.ts
- src/tests/eosjs-jsonrpc.test.ts
Add `send_transaction` to JSON RPC. Fixes #539.
`send_transaction` API is added to a set of supported JSON RPC.
Newly supported `send_transaction` needs to be documented with returned format. Legacy API `push_transaction` has overhead to convert returned data for backward compatibility.
> Add support for send_transaction JSON RPC

- src/eosjs-jsonrpc.ts
- src/tests/eosjs-jsonrpc.test.ts
- Fixes #558
- Also added extra slash in constructor for `eosjs-jsonrpc.test.ts` to confirm that it will remain working
> trimmed off final slash from endpoint with regex

- package.json
- src/eosjs-jssig.ts
- src/eosjs-numeric.ts
- src/tests/eosjs-jssig.test.ts
- yarn.lock
> Replace eosjs-ecc with elliptic

- src/eosjs-api.ts
- src/eosjs-jsonrpc.ts
- src/eosjs-rpc-interfaces.ts
- src/eosjs-serialize.ts
> replace get_block with get_block_header_state

- src/eosjs-api.ts
In response to #584 
The previous PR actually introduced the API changes, but the changes should be backwards compatible for any consumers of the API. This PR will add a fallback which will fix certain cases where `get_block_header_state` will fail
> Get block header fallback

- package.json
Fixes #576 
eosjs-ecc just got a branch merged that fixes ripemd hashing when using the signature provider with applications such as electron. This patch resolves issues while using the signature provider; and bumps the version to 4.0.7 of eosjs-ecc.
This new version of eosjs-ecc includes changes from the last 4 months. The old version excludes these changes and uses a version of eosjs-ecc from a year ago.
> eosjs-ecc version bump to include ripemdhash updates

- package.json
- src/PrivateKey.ts
- src/PublicKey.ts
- src/Signature.ts
- src/eosjs-ecc.d.ts
- src/eosjs-jssig.ts
- src/eosjs-key-conversions.ts
- src/eosjs-numeric.ts
- src/tests/eosjs-jssig.test.ts
- tsconfig.json
- yarn.lock
Adding helper functions to allow for going back and forth from elliptic library.
These are helper functions and refactoring of existing code; should be no impact on the API.
> Add conversion helpers for to/from elliptic lib

- package.json
- yarn.lock
@babel-cli was including @babel-polyfill, which causes problems for any client app that imports babel-polyfill.   Additionally, babel recommends libraries *don't* include the polyfill, given that makes the lib mutate global state.
> Fix Issue #450: Removing babel-cli removes need for babel-polyfill

- package.json
- scripts/copy-ripe-md.js
Added a small script that copies `ripemd.es5.js` to the `dist` folder. Otherwise this repo does not currently work on windows.
> Resolve Copying on Multiplatform

- package.json
- src/Signature.ts
- src/tests/eosjs-ecc-verification.test.js
- src/tests/eosjs-jssig.test.ts
- yarn.lock
Fixing some tiny and critical coding error
> Fixing sign() method

- README.md
- package.json
- src/eosjs-jsonrpc.ts
- src/tests/eosjs-jsonrpc.test.ts
- yarn.lock
merging in default arg fix in prep for next release
> Merging V20.0 fixes into develop in prep for next release

- src/eosjs-serialize.ts
- src/tests/eosjs-serialize.test.ts
Change:
For the validation of data type of bool during serialization, additionally accept number which equal to 1 or 0. Closing https://github.com/EOSIO/eosjs/pull/624 in favor of this PR due to adding tests and switching base branch to `develop`.
Reason of the change:
You could see there is a buffer.push(data ? 1 : 0); just below the changed line. It converts all boolean value to 1 or 0.
Hence, if we fetch the payload in an action which is pushed by eosjs before, all boolean fields would become 1 or 0. If we repeat the same payload with the field using value of 1 or 0, it will be invalidated during the check because the check only accept boolean as the data type.
In our latest eosio-explorer required feature, there is a repeat push action feature which depends on the last fetched payload …
> Accept number equal to 1 or 0 while checking data type of bool.

- src/PrivateKey.ts
- src/PublicKey.ts
- src/Signature.ts
- src/eosjs-jssig.ts
- src/tests/eosjs-ecc-verification-stress.test.js
- src/tests/eosjs-ecc-verification.test.js
- src/tests/eosjs-jssig.test.ts
Adjusting the existing PrivateKey, PublicKey, Signature, and JsSignatureProvider to use p256 r1 format keys if optional arguments are provided, such as the r1 KeyType from numeric and elliptic constructed with p256.  K1 format and secp256k1 are default if no ecurve/keyType are provided.
PrivateKey.getType() => returns private variable this.key.type
PublicKey.getType() => returns private variable this.key.type
Signature.getType() => returns private variable this.signature.type
> Elliptic p256 compatibility support

- src/eosjs-api.ts
- src/tests/eosjs-api.test.ts
Adding a jsonToRawAbi function which acts as the inverse of the rawAbiToJson function.
New jsonToRawAbi in the eosjs-api object
> JsonToRawAbi, inverse of rawAbiToJson

- src/eosjs-jssig.ts
secp256k1's hash() is sha256 from hash.js, its constructor does NOT have any parameter.
> * fix hash() misuse

- .travis.yml
Travis CI configuration would push any tagged branch to latest on npm, which recently affected the tagged release/21.0.x branch that was intended to be an RC and not the latest on npm.  Removing the configuration while the process is reworked.
> Removing latest npm deploy from Travis CI configuration

- .travis.yml
Travis CI configuration would push any tagged branch to latest on npm, which recently affected the tagged release/21.0.x branch that was intended to be an RC and not the latest on npm.  Removing the configuration while the process is reworked.
> Removing the latest deploy from .travis.yml (release/21.0.x branch)

- src/Signature.ts
With the current v21 release candidate, signatures that have less than 32 byte r or s values will generate signatures with lengths less than the 65 bytes necessary.  The r and s need to be zero padded to resolve this issue.  The elliptic library uses bn.js for the r and s values and the .toArray operation has a length argument with the purpose of zero padding the value to the length.
Fixes #663
> Zero padding Signature r-value/s-value to 32 bytes

- src/eosjs-serialize.ts
- src/tests/eosjs-serialize.test.ts
https://github.com/EOSIO/eosjs/issues/665
Validate symbols with the following regex:
- Between 1 and 7 characters
- Only uppercase A-Z characters
> Fix invalid symbol issue

- src/eosjs-serialize.ts
- src/tests/eosjs-serialize.test.ts
#665 
Releasing #666 with v21. 
Validate symbols with the following regex:
- Between 1 and 7 characters
- Only uppercase A-Z characters
> Release 21.0.x validate symbol

- src/Signature.ts
With the current v21 release candidate, signatures that have less than 32 byte r or s values will generate signatures with lengths less than the 65 bytes necessary.  The r and s need to be zero padded to resolve this issue.  The elliptic library uses bn.js for the r and s values and the .toArray operation has a length argument with the purpose of zero padding the value to the length.
> Zero padding Signature r-value/s-value to 32 bytes (release/21.0.x branch)

- docs/basic-usage/00_browser.md
- src/tests/web.html
- webpack.debug.js
- webpack.prod.js
Adjusting the minified and debug files generated by `yarn build-web` to follow minified file convention (*.min.js) to create easier understanding which files should be used in development/production.
Adjusted the browser usage documentation to the new file convention
> Minified file convention

- docs/basic-usage/00_browser.md
- src/tests/web.html
- webpack.debug.js
- webpack.prod.js
Adjusting the minified and debug files generated by `yarn build-web` to follow minified file convention (*.min.js) to create easier understanding which files should be used in development/production.
Adjusted the browser usage documentation to the new file convention
> Minified file convention (release/21.0.x branch)

- docs/00_introduction.md
Fixes #662-- Update to correctly reference new doc version.
> Rename of basic-usage was missed in doc

- src/PublicKey.ts
- src/eosjs-jssig.ts
`The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.`
Resolved by switching usages to `Buffer.from()`
> Resolving deprecation of new Buffer()

- src/PrivateKey.ts
- src/PublicKey.ts
- src/tests/node.js
- src/tests/node.test.ts
- src/tests/web.html
Fixes https://github.com/EOSIO/eosjs/issues/689
> Switching to browser compatible .toArrayLike

- src/eosjs-api.ts
- yarn.lock
Calls to `get_block_header_state` produce errors when calling against a block that is not reversible. This PR reduces the need for those calls.
Don't call `get_block_header_state` whenever possible on `transact`.
Fixes https://github.com/EOSIO/eosjs/issues/702 
Co-Authored By: @UMU618 umu618@hotmail.com
> Remove unnecessary call to get_block_header_state

- src/eosjs-jssig.ts
- src/tests/eosjs-jssig.test.ts
PrivateKey.sign() was changed to hash the data by default without `shouldHash` set to false, JsSignatureProvider code was not changed to accommodate.
> Added false for shouldHash to sign() usages

- src/eosjs-jssig.ts
- src/tests/eosjs-jssig.test.ts
PrivateKey.sign() was changed to hash the data by default without shouldHash set to false, JsSignatureProvider code was not changed to accommodate.
> Added false for shouldHash to sign() usages (release/21.0.x branch)

- src/eosjs-ecc-migration.ts
- src/eosjs-key-conversions.ts
- src/tests/eosjs-ecc-migration.test.ts
- src/tests/eosjs-jssig.test.ts
- yarn.lock
eosjs has a "browser usage" option in the documentation that means building the files with `build-web` and serving those files in the html.  Unfortunately, without webpack or nodejs, that means that it's impossible to set a `process.env` environment variable.  Another alternative option is needed to allow users to run the `generateKeyPair` method.  Code required a `// @ts-ignore` due to TS2339.
It is worth noting that running this command in the browser is unsafe in production environments but developers will likely need this option for development or testing as well.
Resolves https://github.com/EOSIO/eosjs/issues/737
> Adding an alternative option for browser to generate key pairs

- package.json
- yarn.lock
Removing `-rc1` from develop version to better accommodate the new ci/cd versioning for edge releases
> Removing RC1 from develop version

- src/PublicKey.ts
- src/eosjs-jssig.ts
`The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.`
Resolved by switching usages to `Buffer.from()`
> Resolving deprecation of new Buffer() (release/21.0.x branch)

- src/eosjs-api.ts
- yarn.lock
Calls to `get_block_header_state` produce errors when calling against a block that is not reversible. This PR reduces the need for those calls.
Don't call `get_block_header_state` whenever possible on `transact`.
Fixes https://github.com/EOSIO/eosjs/issues/702 
Co-Authored By: @UMU618 umu618@hotmail.com
> Remove unnecessary call to get_block_header_state (release/21.0.x branch)

- src/eosjs-serialize.ts
- src/tests/eosjs-serialize.test.ts
- yarn.lock
To resolve some issues with serialization of names, a regex and error message was added to inform the user what might be wrong with the name in the transaction.
Resolves https://github.com/EOSIO/eosjs/issues/720
> Adding regex to validate name during serialization (release/21.0.x branch)

- src/eosjs-ecc-migration.ts
- src/eosjs-key-conversions.ts
- src/tests/eosjs-ecc-migration.test.ts
- src/tests/eosjs-jssig.test.ts
eosjs has a "browser usage" option in the documentation that means building the files with `build-web` and serving those files in the html.  Unfortunately, without webpack or nodejs, that means that it's impossible to set a `process.env` environment variable.  Another alternative option is needed to allow users to run the `generateKeyPair` method.  Code required a `// @ts-ignore` due to TS2339.
It is worth noting that running this command in the browser is unsafe in production environments but developers will likely need this option for development or testing as well.
Resolves https://github.com/EOSIO/eosjs/issues/737
> Adding an alternative option for browser to generate key pairs (release/21.0.x branch)

- .github/workflows/ci.yml
- README.md
- package.json
- yarn.lock
When merging with protected branches, the yarn.lock updates will fail to push.  This will check if the branch is protected and avoid pushing and failing.
Additionally, the workflow needs to re-run and succeed in order to easily merge.  However, the `github.token` supplied to GitHub Actions will not re-run a workflow if it fires the event to avoid infinite runs of the workflow.  Adding and using a different token will allow the workflow to re-run.  Infinite runs is not an issue for this workflow since it only runs again if there are any updates to the dependencies.
Since forks wouldn't have the token set in their repo secrets but all repos have `github.token` set inside workflows, it was also important to create a conditional that allows the workflow to checkout with either token so …
> Updating CI/CD to check for protected branch and use token so workflow re-runs

- .github/workflows/ci.yml
- README.md
- yarn.lock
When merging with protected branches, the yarn.lock updates will fail to push.  This will check if the branch is protected and avoid pushing and failing.
Additionally, the workflow needs to re-run and succeed in order to easily merge.  However, the `github.token` supplied to GitHub Actions will not re-run a workflow if it fires the event to avoid infinite runs of the workflow.  Adding and using a different token will allow the workflow to re-run.  Infinite runs is not an issue for this workflow since it only runs again if there are any updates to the dependencies.
Since forks wouldn't have the token set in their repo secrets but all repos have `github.token` set inside workflows, it was also important to create a conditional that allows the workflow to checkout with either token so …
> Updating CI/CD to check for protected branch and use token so workflow re-runs (release/21.0.x branch)

- package.json
- src/Signature.ts
- src/eosjs-api-interfaces.ts
- src/eosjs-api.ts
- src/eosjs-jssig.ts
- src/eosjs-key-conversions.ts
- src/eosjs-serialize.ts
- src/eosjs-webauthn-sig.ts
- src/tests/eosjs-api.test.ts
- yarn.lock
Some of the new features (return values) add values that are in a deep location in the transaction result. These new declared types should alleviate some difficulty in finding the values while also adding interfaces to the documentation for developers.
Additionally, there was a fix needed for typescript for the TransactionBuilder
> Additional types for documentation/development

- package.json
- src/eosjs-api.ts
- yarn.lock
There is no need to run `.json()` on the response as it is already a json result and can be accessed directly.  Removing this code to allow query to work as intended.
> Fixing an issue with response from fetch in the query method

- .github/eosjs-ci/Dockerfile
- .github/eosjs-ci/scripts/deploy_contracts.sh
- .github/workflows/ci.yml
- .github/workflows/publish-edge.yml
- .github/workflows/publish-release.yml
- package.json
- yarn.lock
Adding the boot and bios process to eosjs ci/cd as well as required postgres dependency of eos.  Switching from using contracts to change chain parameters to using the actions available in the bios contract.
> Adjusting CI/CD to use new bios/boot systems

- docs/basic-usage/00_browser.md
- package.json
- src/tests/web.html
- webpack.debug.js
- webpack.prod.js
- yarn.lock
Webpack has been packaging external packages with eosjs and there is a requirement to ensure that these external packages are separated in a different file.  Additionally, webpack and tsc needed deletion of the files before they run and we were using rm -rf which is not crossplatform.  Webpack has a plugin that can clean a directory but for tsc, I added rimraf, a cross-platform package for this use case.
Since the vendor files have been moved to `externals.js` and `externals.min.js`, these files must be included when using eosjs in the browser going forward.
_Second PR to cherry pick commits to release/22.0.x branch_
Added a note that `externals.js` or `externals.min.js` are now required to be added in order to use eosjs
> Webpack separating external packages and cross-platform building (release/22.0.x)

- .github/workflows/build-docker.yml
- .github/workflows/integration-test.yml
- yarn.lock
Cron in scheduled workflows was not set to run on the zero of the hour so they run five times during the hour.
> Adjusting scheduled workflows cron (develop branch)

- .github/eosjs-ci/Dockerfile
- .github/eosjs-ci/contracts/cfhello.cpp
- .github/eosjs-ci/scripts/deploy_contracts.sh
- .github/workflows/build-docker-develop.yml
- .github/workflows/build-docker-release.yml
- .github/workflows/ci.yml
- .github/workflows/integration-test-develop.yml
- .github/workflows/integration-test-release.yml
- .github/workflows/publish-release.yml
Adjusting the workflows to add two new pipelines to build and test with the release branches. Also changed the existing files to rename them to develop. Adjusted the dockerfile to take build arguments specifying which branches to use for eos and cdt. Lastly, changed the release stable, prerelease, and edge release workflows to have similar code.
_CI pipeline uses release_22.0.x docker tag for this branch specifically_
> Adding two pipelines for release branch for ci/cd (release 22.0.x)

- .github/eosjs-ci/Dockerfile
- yarn.lock
eosio/eos image on docker is no longer updated which is causing the error in the integration tests.  Switching to eosio/eosio will resolve the issue.  This change needs to be done in develop as well so it is not overwritten in the future.
> Switching to eosio/eosio docker image in CI/CD

- .github/eosjs-ci/Dockerfile
eosio/eos image on docker is no longer updated which is causing the error in the integration tests. Switching to eosio/eosio will resolve the issue.
> Switching to eosio/eosio docker image in CI/CD (release/22.0.x)

- package.json
- src/eosjs-serialize.ts
- src/tests/eosjs-serialize.test.ts
- yarn.lock
There was an error in the regex for eosio::name in eosjs-serialize.  While there is a workaround to allow developers to use `...` as a replacement, it would be better to include this fix in a patch release for v21.
Backporting a fix that is in eosjs@edge and eosjs@RC to eosjs v21
> Allowing a name to be an empty string

- .github/dependabot.yml
Unfortunately Github's built-in dependabot is missing two crucial features that would allow easier use: Grouping of PRs instead of separate PRs per dependency, and filtering updates to specific types.
Filtering updates was available in the old dependabot which still has documentation that unfortunately isn't correct for Github's built-in version.  This would be fine if it was also possible to group weekly dependency updates into one PR, but unfortunately without these two features, dependabot will open too many PRs too frequently.
The CI/CD workflow has a task that updates all dependencies, as long as commits/PRs are actively being created, this will suffice until dependabot gets more features.  Additionally, security updates will need to stay open against master (until a release solves …
> Removing NPM ecosystem from dependabot settings file

- .github/dependabot.yml
- .github/eosjs-ci/Dockerfile
- .github/eosjs-ci/scripts/deploy_contracts.sh
- .github/workflows/build-docker-images.yml
> Updating default branch with new ci/cd and dependabot settings

- .github/workflows/ci.yml
- .github/workflows/integration-tests.yml
- .github/workflows/publish-edge.yml
- .github/workflows/publish-release.yml
Due to one of our sub-dependencies, it's advised to update our ci/cd workflow code to `"^12.20 || ^14.14.0 || ^16"`.  Since WebCrypto still requires v15/v16, we can move to v16.  Additionally, the nodejs github action has the ability to support the latest released version of nodejs for particular versions by specifying `'16'` as the node-version: https://github.com/actions/setup-node#supported-version-syntax
> Updating workflow nodejs versions to v16, replacing the matrix strategy

- package.json
- src/KeyUtil.ts
- src/eosjs-key-conversions.ts
- src/eosjs-webcrypto-sig.ts
- yarn.lock
The default interface for CryptoKey from the crypto node lib can be optional for both private and public key.  Since generateWebCryptoKey generates both due to the curve used, it would be better to define the interface as both non-optional.
> Overriding the cryptokey interface to ensure priv/pub keys are not optional

- docs/01_technical-overview.md
- docs/how-to-guides/01_how-to-submit-a-transaction.md
- package.json
- src/eosjs-api.ts
- src/eosjs-jsonrpc.ts
- src/eosjs-rpc-interfaces.ts
- src/tests/eosjs-api.test.ts
- src/tests/node.js
- src/tests/web.html
- yarn.lock
Now that return failure traces is available on /v2/chain/send_transaction and send_transaction is the more efficient method, api.transact now has a `sendSignedTransaction` method that directs the signed transaction dependent on whether it's read only and whether /v2/chain/send_transaction is available on the nodeos endpoint, otherwise it falls back to v1.
api.transact no longer uses push_transaction (breaking change)
api.sendSignedTransaction: method to send a signed transaction to either v1 send_transaction, v2 send_transaction or send_ro_transaction.
Adjusted docs to reflect the change from push_transaction to any three endpoints depending on read-only or nodeos version.  Additionally added a section for return failure traces now that it is available for v2 send_transaction as well
> Adjusting eosjs to use send_transaction or send_transaction_v2 depending on nodeos

- .github/workflows/integration-tests.yml
We removed two runs of test-types when the nodeos version and eosjs version had changed for certain matchups.  Unfortunately did not remove the coverage file copy command as well so integration tests have been failing with "no file exists".
> Removing coverage file for test types following previous work
