EOSIO/eosjs

src/write-api.js
This depends on https://github.com/EOSIO/eosjs-fcbuffer/pull/4 and https://github.com/EOSIO/eosjs-json/pull/5
=> update transaction to dawn-v3.0.0

README.md
Pretty sure this won't qualify me for a bug bounty 😂
=> Fixed some minor typos. You are welcome.

package-lock.json, package.json, src/index.js
This patch makes eosjs compatible with other environments. (ionic3 in my case)
=> remove polyfill from source

docker/README.md
added `unalias cleos` for people who followed the instructions from the eosio dev docs and got an Error: No such container: eosio
=> added `unalias cleos`

src/structs.js
This PR provides coherent code format for semicolons based on current code styles.
=> Coherent code format for semicolon

README.md
=> Move test docs to the bottom; Link to browser docs

README.md
=> Add clarifying warning about new version; add install command

.travis.yml, scripts/is_latest.sh, scripts/publish.sh
Allows new versions of eosjs to be released via tag creation against master.  This will automatically update the package.json and deploy to npm.
=> Allows tag based deployments

src/eosjs-jsonrpc.ts, src/tests/eosjs-jsonrpc.test.ts
[Issue link](https://github.com/EOSIO/eosjs/issues/412)
=> added secondary key support for get_table_rows #412

.babelrc, package.json, src/index.ts
=> remove polyfill from src

README.md, docs/2.-Transaction-Examples.md
Several deficiencies in documentation with respect to `default exports` have been corrected. 
Resolves #423 
Resolves #474
=> Fix documentation deficiencies resulting from default exports

src/eosjs-jsonrpc.ts, src/tests/eosjs-jsonrpc.test.ts
[Issue 503](https://github.com/EOSIO/eosjs/issues/503)
=> add get_table_by_scope to eosjs

src/eosjs-numeric.ts
=> removing const to prevent compilation error in certain TS projects

src/eosjs-api.ts
=> Support context-free actions

docs/4.-Reading blockchain-Examples.md
Documentation update. Example json was invalid due to some missing commas between attributes and a few incorrect attribute definitions (`=` instead of `:`). No other impact.
Nothing further needs to be added after merge.
=> Minor bugfix for invalid example json in documentation

src/eosjs-jsonrpc.ts, src/tests/eosjs-jsonrpc.test.ts
Fix Issue #390, by properly defaulting `code_as_wasm` parameter
=> Fix Issue #390

README.md
Fix #372: Adding badges to README
=> Fix #372: Added license, version, and build passing badges

docs/how-to-guides/06_how-to-deploy-a-smart-contract.md
This changes one line of the documentation to match with example code snippets used above in the file.
This change makes a bug fix in the `docs/how-to-guides/06_how-to-deploy-a-smart-contract.md` documentation to use **wasmHexString** rather than **wasmFilePath** in the code field of the data field of a transaction.  See [this issue](https://github.com/EOSIO/eosjs/issues/608) for more information.
=> bugfix.  Changing wasmFilePath to wasmHexString in full code example

src/Signature.ts, src/tests/eosjs-ecc-verification-stress.test.js, src/tests/eosjs-jssig.test.ts, yarn.lock
=> Cleanup for release

package.json
=> Bump version to 21-rc1

docs/00_introduction.md
Fixes https://github.com/EOSIO/eosjs/issues/662 -- Update to correctly reference new doc version.
=> Rename of basic-usage was missed in doc

package.json
=> Version bump for RC2

src/PrivateKey.ts, src/PublicKey.ts, src/tests/node.js, src/tests/node.test.ts, src/tests/web.html
=> Switching to browser compatible .toArrayLike (release/21.0.x branch)

docs/01_technical-overview.md
=> Fix broken link to intro page

src/eosjs-serialize.ts, src/tests/eosjs-serialize.test.ts, yarn.lock
To resolve some issues with serialization of names, a regex and error message was added to inform the user what might be wrong with the name in the transaction.
Resolves https://github.com/EOSIO/eosjs/issues/720
=> Adding regex to validate name during serialization

LICENSE
=> 2020 License

.github/workflows/publish-release.yml, package.json, yarn.lock
=> Fixing the publish-release workflow's docker version

docs/4.-Reading blockchain-Examples.md
Update the secondary key example using the correct parameters
Fixe #727
=> Update the secondary key example

docs/4.-Reading blockchain-Examples.md
Fix some JS syntax errors.
Fix #725
=> Fix some JS syntax errors

package.json, yarn.lock
=> Bumping version to `-rc3`

package.json, yarn.lock
Bump elliptic version due to security vulnerability
=> Bump elliptic - v21

package.json, yarn.lock
Bump elliptic version due to security vulnerability
=> Bump elliptic - edge

package.json
=> Bump RC version

package.json, yarn.lock
=> Updating version to 21.0.2

README.md, package.json, scripts/copy-ripe-md.js
=> Merging changes from master branch to release/21.0.x

docs/how-to-guides/01_how-to-submit-a-transaction.md, package.json, yarn.lock
Documentation explaining how to access deserialized action return values.  Documentation for https://github.com/EOSIO/eosjs/pull/778
=> Documentation for action return values

package.json, src/abi.abi.json, yarn.lock
Adding `return_values` specifically for now.  More additions might be needed for other planned features.
=> Updating `abi.abi.json` to eosio::abi/1.2

docs.json, package.json, yarn.lock
update docs.json for remove_extension filter addition
=> [docs] update docs.json for remove_extension filter

package.json, yarn.lock
=> Bumping version to 21.0.3

package.json, yarn.lock
=> Bumping develop version to 21.1.0

package.json, yarn.lock
=> Bumping the version to 22.0.0-rc1

.github/eosjs-ci/Dockerfile, .github/eosjs-ci/scripts/deploy_contracts.sh, .github/workflows/ci.yml, .github/workflows/publish-edge.yml, .github/workflows/publish-release.yml, package.json, yarn.lock
Adding the boot and bios process to eosjs ci/cd as well as required postgres dependency of eos.  Switching from using contracts to change chain parameters to using the actions available in the bios contract.
_Second PR to cherry pick commits to release/22.0.x branch_
=> Adjusting CI/CD to use new bios/boot systems (release/22.0.x)

.github/workflows/build-docker.yml, .github/workflows/integration-test.yml
Cron in scheduled workflows was not set to run on the zero of the hour so they run five times during the hour.
=> Adjusting scheduled workflows cron

.github/eosjs-ci/Dockerfile, .github/workflows/build-docker-develop.yml, .github/workflows/build-docker-release.yml, .github/workflows/ci.yml, .github/workflows/integration-test-develop.yml, .github/workflows/integration-test-release.yml, .github/workflows/publish-release.yml, package.json, yarn.lock
Adjusting the workflows to add two new pipelines to build and test with the release branches.  Also changed the existing files to rename them to develop.  Adjusted the dockerfile to take build arguments specifying which branches to use for eos and cdt.  Lastly, changed the release stable, prerelease, and edge release workflows to have similar code.
=> Adding two pipelines for release branch for ci/cd

.github/workflows/build-docker-develop.yml, .github/workflows/build-docker-release.yml, .github/workflows/integration-test-develop.yml, .github/workflows/integration-test-release.yml
Adjusting the workflows to add two new pipelines to build and test with the release branches. Also changed the existing files to rename them to develop.
_Only workflow files needed in the default branch_
=> Adding two pipelines for release branch for ci/cd (default branch)

docs/how-to-guides/09_how-to-get-table-information.md, yarn.lock
Slightly changed the documentation to fix a typo and adjust the first example to use indexValue instead of lowerBound and upperBound
=> Updating first example to use indexValue in key value documentation

package.json, yarn.lock
=> Bumping version to 21.0.4

.github/dependabot.yml
=> Adding dependabot.yml settings file to configure Dependabot

.github/dependabot.yml
Updating dependabot to only update github actions weekly (avoiding the master branch due to ci/cd, updates will reach master from releases) and restrict the updates for npm to security updates.
=> Update dependabot with more settings

docs/how-to-guides/09_how-to-get-table-information.md
Slightly changed the documentation to fix a typo and adjust the first example to use indexValue instead of lowerBound and upperBound.  Additionally removed `expReturn` from the examples.
=> Adjusting the eosjs key value documentation (release/22.0.x branch)

package.json, yarn.lock
=> Bumping version to v22.0.0

.github/dependabot.yml
=> Merging master into release/22.0.x

package.json, yarn.lock
=> Bumping version to v22.1.0

.github/workflows/ci.yml, .github/workflows/integration-test-develop.yml, .github/workflows/integration-test-release.yml, .github/workflows/publish-edge.yml, .github/workflows/publish-release.yml
=> Adjusting version of node-version in github workflows

cypress/integration/index.spec.js, package.json, src/tests/node.test.ts, src/tests/web.html, yarn.lock
=> Separates the web tests to separate tests and adds conditionals

package.json, yarn.lock
=> Version bumping develop to 22.2.0

.github/workflows/ci.yml, .github/workflows/publish-edge.yml, .github/workflows/publish-release.yml, package.json, src/eosjs-api.ts, src/eosjs-serialize.ts, src/tests/eosjs-api.test.ts, yarn.lock
Transaction extensions were deserialized to `[1, '']` while they should be `[ [1, ''] ]`. Resolved with the change to `deserializePair`.  Additionally, the type response for `deserializeTransactionExtensions` was changed to be better defined.
Added test to check `deserializePair` changes.
_Cherry picking commits for release/22.1.x branch_
=> Resolving issue with transaction extension deserialization (release/22.1.x)

.github/workflows/build-docker-images.yml, .github/workflows/ci.yml, .github/workflows/publish-edge.yml, .github/workflows/publish-release.yml
Instead of firing off workflows without credentials and getting too far in the workflow before failing, this functionality will check that the credentials exist before continuing to large processing tasks like building docker.
Additionally changed CI to not push/commit dependency updates if dependabot[bot] created the commit since they do not have access to push/commit but this change needs to be replicated to all active branches (release/22.0.x, release/22.1.x, and develop).
=> Adjusting CI/CD to check for credentials before starting certain workflows

.github/eosjs-ci/Dockerfile, .github/eosjs-ci/scripts/deploy_contracts.sh, .github/workflows/build-docker-images.yml, .github/workflows/integration-tests.yml, .github/workflows/publish-edge.yml
- Adds code coverage for every integration test nightly
- Re-adds the nodeos 2.0.x docker build since it is still tested in integration tests
- Adds integration tests for new release/22.1.x release branch
=> CI/CD Changes (Code Coverage, Re-adding 2.0.x docker build, adding integration tests for release/22.1.x)

package.json, yarn.lock
CI/CD reported that set-value and ansi-regex currently have vulnerabilities.  Since these are sub-dependencies of other dependencies we use, this was resolved using resolutions for these two projects
=> Adding resolutions for set-value and ansi-regex, updating dependencies

package.json, src/eosjs-rpc-interfaces.ts, src/tests/type-checks.test.ts, yarn.lock
=> Adding new types to get_info response

package.json, src/eosjs-rpc-interfaces.ts, src/tests/type-checks.test.ts, yarn.lock
=> Adding new types to get_info and trace get_block

.github/eosjs-ci/Dockerfile, .github/eosjs-ci/scripts/deploy_contracts.sh, .github/workflows/integration-tests.yml
=> Adding CICD changes for nested container tests

package.json, src/eosjs-rpc-interfaces.ts, src/tests/type-checks.test.ts, yarn.lock
=> Adding new types to get_info

.github/workflows/integration-tests.yml
=> Adding test-types for release/22.0.x using nodeos release/2.1.x

.github/workflows/integration-tests.yml
=> Removing nested containers step from Integration Tests workflow
